
@urlDev= http://localhost:8088

### signup
POST {{urlDev}}/shop/signup HTTP/1.1
Content-Type: application/json
x-api-key: d9c34385-64f0-4619-b6ef-53c7ddc46be4

{
    "name": "shop acb",
    "email": "shop_abc@gmail.com",
    "password": "123"
}

### login
POST {{urlDev}}/shop/login HTTP/1.1
Content-Type: application/json
x-api-key: d9c34385-64f0-4619-b6ef-53c7ddc46be4

{
    "email": "shop_abc@gmail.com",
    "password": "123"
}


### logout
POST  {{urlDev}}/shop/logout HTTP/1.1
x-api-key : d9c34385-64f0-4619-b6ef-53c7ddc46be4
x-client-id: 656cdd028f9e4d252ec953c5
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjYmE5Yzg3YzBlMTk1ODA0NTJhMzgiLCJlbWFpbCI6InNob3BfYWJjQGdtYWlsLmNvbSIsImlhdCI6MTcwMTYyNzUxMiwiZXhwIjoxNzAxODAwMzEyfQ.oIkrn2SS-Jm8qWdecvZ4IrnbNs0r8mIxvnm6Jm0sJnyRpA9Wb72lwG75ju_awbMOKQUTGU12jZqx3RWo8KhGOjvD-KCx_xbcAjtHzU1H2aBrOFgypg5qKmLnaKRwQTS2rb_Xm6sLMSCyfYNMyYjxwooDrsxhgApUgerYVExSwfGinBb0TfFqfeT97wLL-7BQvVTjVTp5_cdMphR50RpjTq1wL9oJsrQKBuLQakj-lYwP5TesCYrYUAZCAWlzeX8gPKLFqlrE1fui__LQDm3oUFhUcC8RerGFmKG7wuE4QaMIOMz6RydPmpe4np4eW0r-wGd_t09FOlRJ6hsBmXJblUVVgveApQaqys8ROjZItlzbyFAfhnjpQKynTl-9EKnGkI8JHz7xgpVrXnyYUO_oPPYJRbq_omRC11fR4UQewxICpTQgfRCq5orVGp_YuQvIicwD987g5KTA8DReTWloE7seOd6kroxHaXgKdjcA3DdAj9cBEzn0iS5sotshccHYsGXgMX1qbJHR2jRbhAGNNKGb7ltpZFYEPl5vPzQ4nfOF5tBxqa4jTQyuClEQqHeg64XEU5ZJ4IOQx9UuHQcVm84ONYhtL5yLIRv0HumQ7dPknq6w7EM-rOAb4XRkXw6LheplI7wxH71nVjV7DvgVXq_n73LmeDdr0Mv_kSZPUvg


### handlerRefreshToken
POST {{urlDev}}/shop/handlerRefreshToken HTTP/1.1
Content-Type: application/json
x-api-key : d9c34385-64f0-4619-b6ef-53c7ddc46be4
x-client-id: 656ce671b1fb4318a23dad16
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjZTY3MWIxZmI0MzE4YTIzZGFkMTYiLCJlbWFpbCI6InNob3BfYWJjQGdtYWlsLmNvbSIsImlhdCI6MTcwMTYzNTgwNywiZXhwIjoxNzAxODA4NjA3fQ.RCVvP-VPWJTtacRu5ySO_8FM2NgAIcAzgTODbV-DdT27ksJr6DWe-r1FiPvL8KEnmQuHB07SwJu2z_le_oj9EvsVlW8XnaY41LUby7WSGYZyygFxtLaeQ0EtqLEl6kQFPuKsTbxVH2_y5yrWshffjU0fLazhLrcxwEsmE6kVFG4uE0Bsg0pnNCoMOgkwH1WKF5xoRRpM2Yq-3eFvtUry1Ahtka5jlbPc9FQuynRrhLXC-YC5yOZKXNcyA4KUbIZiuQxUGrA9_RqCr1kKHdVl6NmrV7p_G_ea6Ya7XaHcSVVSXmKkUVaI9JGqAzsIhIlLKnx7laMbKWNzZ-0F61NE1qwRqt67XirGqGG8lLXX5NPxiQFx_oKoVC90q4Li6ImtCnGiNoYZRdcz17QhbpSXuPwMBT0nz-AYOrvMopN1h6UKmE-_7jq_0r6xFnsFCX-i4hupV0YZDqeO9bZSXyNkfrftZwBR1zoXv9jYFHlk9hm4PWq4708e_2jQJvPGkh7hpnkXu5ZZPPs3F8DxIuu53SccJXPqrywnCp6cF6uf4Nsv1WnuA03Lhvz-wJHxZEFMaANUVXIL-GeJPDOwRuaaWF1_VjM1WqMOJD1nVsWRBj34X7BCBptRvWTIa0vxLp7gBiLwJGiREkTBLjtmf8H_KA4DZPLqATQdotqy_A9V5qY

{
 "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZjZTY3MWIxZmI0MzE4YTIzZGFkMTYiLCJlbWFpbCI6InNob3BfYWJjQGdtYWlsLmNvbSIsImlhdCI6MTcwMTYzNTgwNywiZXhwIjoxNzAyMjQwNjA3fQ.o1026C_TdryRbBvQ5KTvV_nOqqrFutpDYCrf3l7Ivb67oyf8LoVhmM_aThj2QG3iUoDzmgqWdzE3VDmVK27vLJ7p0CF_eZv2oG_W8WLyvezg9vy7Y5VCtT1on-8-b9R1wV-_WZD1Chwug-dKJ6w-0opqNWBZIsD4aFjfJ5V_LzMwVyOksA4BtMrbni0VcRM1Fvl44_OwRFGPHS4PJlYUvkn2bJTX5LJ5afnpJ__eOgaSaOlAxAuAkfeAfMw91AAN5uZh3X0qRLzfPDu_YsIq5tmTqNszg_KbaXqhojQebKAxG0Mxt0jm0XAfOPYIfUoYDkEsL-oyduQbnBrhlcVC_L3TR2Nyg-bONS6wykhmXt-1K_RFRXmXqWHefEDvIoNLoCLzTcnlD0mwWipgfvCj-5vw0BQTXOUYzKtVgfN8BQeDuUvG9cFl0APk_T_tvOztqkPa68S8W4yiwLbhDc6rSsxGxcNIg38egLTUjgmMUAOyJaheRA2AGbAJj6kuwJe3uaSM5jKuRxgoxMvk2oScMMFtwwpnoJiTEwqT6J47GhnvGVAh0LjxPSK0MqsfABLjjjq_DpdUM2iCSLwXnVS4Q3EceGh122iFdhK5HGG8hTGSdpeV8Rc_rvte-IrRJgQRnrGeuMgzwtCPShy8MhjKauhegIjEY2T_AUTYrm2RD9I"
}

