# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Shopaa

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        

        steps:
            - name: Enviroment variables
                - run: |
                   echo "PORT: ${{PORT}}"

                   echo "GOOGLE_CLIENT_ID: ${{GOOGLE_CLIENT_ID}}"
                   echo "GOOGLE_CLIENT_SECRET: ${{GOOGLE_CLIENT_SECRET}}"

                   echo "FACEBOOK_CLIENT_ID: ${{FACEBOOK_CLIENT_ID}}"
                   echo "FACEBOOK_CLIENT_SECRET: ${{FACEBOOK_CLIENT_SECRET}}"

                   echo "CLOUDINATY_NAME: ${{CLOUDINATY_NAME}}"
                   echo "CLOUDINATY_API_KEY: ${{CLOUDINATY_API_KEY}}"
                   echo "CLOUDINATY_API_SECRET: ${{PORT}}"

                   echo "AWS_BUCKET_NAME: ${{AWS_BUCKET_NAME}}"
                   echo "AWS_BUCKET_ACCESS_KEY: ${{AWS_BUCKET_ACCESS_KEY}}"
                   echo "AWS_BUCKET_ACCESS_SECRET: ${{AWS_BUCKET_ACCESS_SECRET}}"
                   echo "AWS_BUCKET_ACCESS_REGION: ${{AWS_BUCKET_ACCESS_REGION}}"

                   echo "MONGO_URI_ATLAS_TEST: ${{MONGO_URI_ATLAS_TEST}}"

                   echo "REDIS_PASSWORD: ${{REDIS_PASSWORD}}"
                   echo "REDIS_HOST: ${{REDIS_HOST}}"
                   echo "REDIS_PORT: ${{ REDIS_PORT}}"
        
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm ci
