# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Shopaa

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        environment: production
        env:
            PORT: ${{ secrets.PORT }}

            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

            FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
            FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}

            CLOUDINATY_NAME: ${{ secrets.CLOUDINATY_NAME }}
            CLOUDINATY_API_KEY: ${{ secrets.CLOUDINATY_API_KEY }}
            CLOUDINATY_API_SECRET: ${{ secrets.CLOUDINATY_API_SECRET }}

            AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
            AWS_BUCKET_ACCESS_KEY: ${{ secrets.AWS_BUCKET_ACCESS_KEY }}
            AWS_BUCKET_ACCESS_SECRET: ${{ secrets.AWS_BUCKET_ACCESS_SECRET }}
            AWS_BUCKET_ACCESS_REGION: ${{ secrets.AWS_BUCKET_ACCESS_REGION }}

            MONGO_URI_ATLAS_TEST: ${{ secrets.MONGO_URI_ATLAS_TEST }}

            REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
            REDIS_HOST: ${{ secrets.REDIS_HOST }}
            REDIS_PORT: ${{ secrets.REDIS_PORT }}

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm ci

            - run: |
                  touch .env
                  echo "${{ secrets.MY_ENV }}" >> .env

            - run: pm2 restart shopa
